FROM python:3.7.9

COPY nivelmaggie.py /app/
COPY requirements.txt /app

WORKDIR /app/

RUN mkdir Homer
RUN mkdir Lisa
RUN mkdir General

RUN pip install -r requirements.txt

CMD ["python","nivelmaggie.py"]


